# Generated by Django 6.0.4 on 2026-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(choices=[('Informatique', 'Informatique'), ('Physique', 'Physique'), ('Mathematiques', 'Mathematiques'), ('Chimie', 'Chimie'), ('Genie Civil', 'Genie Civil'), ('Electronique', 'Electronique')], max_length=40)),
                ('year', models.CharField(max_length=20)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Diplome', 'Diplome'), ('Soutenance', 'Soutenance')], default='Actif', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('birth_date', models.CharField(blank=True, default='', max_length=40)),
                ('formation', models.CharField(blank=True, default='', max_length=200)),
                ('inscription_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
